# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint with Gradle
        run: ./gradlew ktlintcheck
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Print Home
        run: echo $HOME
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: orchestra-lib-artifact
          path: $HOME/work/orchestra_library/orchestra-library/backend/build/
      - name: Test with Gradle
        run: ./gradlew test


